// Functional smoke tests — run inside harness scope (app globals available)
let __n = 0;
function t(name, cond) { __n++; if (!cond) { console.error('FAIL ' + name); process.exitCode = 1; } else console.log('PASS ' + name); }
const isHex = s => /^[0-9a-f]{6}$/.test(s);
t('hsl roundtrip', (() => { const h = hexToHsl('2a9d8f'); return isHex(hslToHex(h.h, h.s, h.l)); })());
t('black/white contrast ~21', contrastRatio('000000', 'ffffff') > 20.9 && contrastRatio('000000', 'ffffff') < 21.1);
t('onColor picks', onColor('ffffff') === '#141414' && onColor('000000') === '#ffffff');
t('colorName', typeof colorName('ff0000') === 'string' && colorName('ff0000').length > 0);
for (const m of ['random', 'pastel', 'vivid', 'warm', 'cool', 'light', 'dark', 'mono'])
  t('genHex ' + m, isHex(genHex(m, 200)));
t('mono hue-ish', (() => { const { h } = hexToHsl(genHex('mono', 200)); const d = Math.abs(h - 200); return Math.min(d, 360 - d) < 25; })());
t('defaults loaded', colors.length === 5 && colors.every(c => isHex(c.hex)));
generate();
t('generate keeps count', colors.length === 5);
t('paletteName set', typeof paletteName === 'string' && paletteName.includes(' '));
t('randName shape', randName().split(' ').length === 2);
t('slug', slug('Velvet Lagoon!') === 'velvet-lagoon');
const before = colors.map(c => c.hex).join();
generate();
const changed = colors.map(c => c.hex).join();
undo();
t('undo restores', colors.map(c => c.hex).join() === before);
redo();
t('redo restores', colors.map(c => c.hex).join() === changed);
pushHistory();
moreAction('sortHue');
t('sortHue sorted', (() => { const hs = colors.map(c => hexToHsl(c.hex).h); return hs.every((h, i) => i === 0 || hs[i - 1] <= h); })());
moreAction('reverse'); moreAction('shuffle'); moreAction('sortLight');
t('sortLight lightest-first', (() => { const ls = colors.map(c => hexToHsl(c.hex).l); return ls.every((l, i) => i === 0 || ls[i-1] >= l); })());
const _pin = colors[2].hex;
colors[2].locked = true;
moreAction('sortHue');
t('sort pins locked strips', colors[2].hex === _pin);
moreAction('lockToggle');
t('lock-all locks all', colors.every(c => c.locked));
moreAction('lockToggle');
t('lock-all unlocks all', colors.every(c => !c.locked));
colors[2].locked = false;
moreAction('sortHue');
t('sortHue toggles back', (() => { const hs = colors.map(c => hexToHsl(c.hex).h); return hs.every((h, i) => i === 0 || hs[i - 1] <= h); })());
moreAction('sortLight');
t('sortLight toggles', (() => { const ls = colors.map(c => hexToHsl(c.hex).l); return ls.every((l, i) => i === 0 || ls[i-1] <= l); })());
t('remix keeps colors', colors.length === 5 && colors.every(c => isHex(c.hex)));
const w1 = paletteFromWord('ocean', 5), w2 = paletteFromWord('ocean', 5);
t('word deterministic', w1.join() === w2.join());
t('word valid hex', w1.every(isHex));
t('ocean is blue', w1.every(h => { const { h: hh } = hexToHsl(h); return hh > 170 && hh < 240; }));
t('multi-word', paletteFromWord('neon desert', 7).length === 7);
t('empty word', paletteFromWord('', 4).length === 4);
for (const [label, m] of VISION) t('vision ' + label.split(' ')[0], isHex(simulateVision('ff6b6b', m)));
t('tailwind', buildTailwind().includes('theme.extend.colors') && buildTailwind().includes('#'));
t('scss', buildScss().split('\n').length === colors.length && buildScss().startsWith('$'));
t('json', JSON.parse(buildJson()).colors.length === colors.length);
t('gradient', buildGradient().startsWith('background: linear-gradient'));
t('svg', buildSvg().startsWith('<svg') && buildSvg().endsWith('</svg>'));
setPalette(['ff0000', '00ff00', '0000ff', 'ffff00', 'ff00ff', '00ffff', '123456', 'abcdef', '111111', '222222']);
t('setPalette clamps to 9', colors.length === 9);
setPalette(['ff0000']);
t('setPalette pads to 2', colors.length === 2);
t('MOOD entries valid', Object.values(MOOD).every(v => Array.isArray(v) && v.length === 4));
t('PRESETS valid', PRESETS.length === 20 && PRESETS.every(p => p.colors.length === 5 && p.colors.every(isHex)));
t('genTheme default', genTheme === 'random' && GEN_THEMES.length === 8);
t('colorName basics', colorName('ff0000')==='Red' && colorName('0000ff')==='Blue' && colorName('ffffff')==='White' && colorName('000000')==='Black');
t('name pool deep', NAMED.length > 800);
t('colorName dedupes', (() => { const u = new Set(['Red']); return colorName('ff0000', u) !== 'Red' && u.size === 2; })());
t('NAMED has 200+ names', NAMED.length >= 200);
t('blendHex valid', isHex(blendHex('ff0000','0000ff')) && isHex(blendHex('ffffff','000000')));
t('blendHex midpoint', (()=>{ const {h}=hexToHsl(blendHex('ff0000','0000ff')); const d=Math.abs(h-300); return Math.min(d,360-d)<15; })());
t('blendHex wraps hue', (()=>{ const {h}=hexToHsl(blendHex(hslToHex(350,80,50),hslToHex(10,80,50))); const d=Math.abs(h-0); return Math.min(d,360-d)<15; })());
t('blendHex grays stay gray', hexToHsl(blendHex('888888','bbbbbb')).s < 10);
openEdit(0);
const eb0 = editBackup;
colors[0].hex = '123456';
inlineDone();
t('inline done keeps', colors[0].hex === '123456' && editIndex === -1);
undo();
t('inline session undoes once', colors[0].hex === eb0);
openEdit(1);
const eb1 = editBackup, ulen = undoStack.length;
colors[1].hex = 'abcdef';
inlineCancel();
t('inline cancel reverts clean', colors[1].hex === eb1 && undoStack.length === ulen - 1 && editIndex === -1);
const mm0 = colors[0].hex, mm1 = colors[1].hex;
moveStrip(0,1);
t('moveStrip swaps', colors[0].hex === mm1 && colors[1].hex === mm0);
const _lk0 = colors[0].locked, _lk1 = colors[1].locked;
colors[0].locked = true; colors[1].locked = false;
moveStrip(0,1);
t('move carries lock with color', colors[0].locked === false && colors[1].locked === true);
moveStrip(0,1);
colors[0].locked = _lk0; colors[1].locked = _lk1;
undo();
t('move undo restores', colors[0].hex === mm0 && colors[1].hex === mm1);
const chd=(a,b)=>Math.max(...[0,2,4].map(i=>Math.abs(parseInt(a.substr(i,2),16)-parseInt(b.substr(i,2),16))));
t('vision preserves white/black', ['protan','deutan','tritan'].every(k => chd(simulateVision('ffffff',k),'ffffff')<=1 && simulateVision('000000',k)==='000000'));
t('vision goldens', simulateVision('ff0000','protan')==='5e5e0c' && simulateVision('ff0000','deutan')==='939300' && simulateVision('0000ff','tritan')==='006288');
t('achroma luminance', simulateAchroma('ffffff')==='ffffff' && simulateAchroma('808080')==='808080' && simulateAchroma('00ff00')==='dbdbdb');
console.log('---'); console.log(process.exitCode ? 'SMOKE FAILED' : `ALL ${__n} SMOKE TESTS PASSED`);
